pipeline
{
  agent any
  stages
  {
    stage('build')
    {
      steps
      {
        echo "Build Process is completed successfully."
      }
    }

    stage('test')
    {
      steps
      {
        echo "Test Process is completed successfully."
      }
    }

    stage('deploy')
    {
      steps
      {
        echo "Deploy Process is completed successfully."
      }
    }
    
  }
  
}
